### ISSUE TITLE
Login expects the "Stay signed in" page but this can be turned off at tenant level

### ISSUE THREAD

**Issue by mookmac** [estruyf/playwright-m365-helpers#2]
The login function expects the "Stay signed in" prompt after entering credentials. However this functionality can be turned off in Entra ID by Global Administrators: [https://learn.microsoft.com/en-us/entra/fundamentals/how-to-manage-stay-signed-in-prompt](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-manage-stay-signed-in-prompt). In this scenario, the login function will sit on this await until it times out and fails.

Suggestion is to make this block optional, controlled by an input parameter 
```
await page
    .locator(`input[type=submit][value=${staySignedInBtnValue}]`)
    .click();
```

**Comment by estruyf** [comment]
Thanks, @mookmac. That makes sense. I have added the code for the optional `stay signed in` behavior. There is no need for an input parameter.

Feel free to try it out in version 0.0.4

**Comment by mookmac** [comment]
thanks for looking at this. I've tested 0.0.4 and now it just hits the 500ms timeout which then causes the "test" to fail. I had a quick search and noticed an active thread on the playwright project requesting a way around this: https://github.com/microsoft/playwright/issues/28542
There's a couple of other suggested approaches here which may be suitable?

**Comment by estruyf** [comment]
In that case, I'll try my first idea. Thanks for testing!

New version 0.0.5 contains a different approach.

**Comment by mookmac** [comment]
0.0.5 works perfectly! thank you very much!

**Comment by estruyf** [comment]
Thanks @mookmac for testing. 🙏
